# This file is used to build the webapp image for deployment.
# The COUNTS_MSG_TYPES and DOT_NAME variables must be set in .env before building to populate
# correctly in the deployed webapp as they are build-time variables.
version: '3'
services:
  cvmanager_webapp:
    build:
      context: webapp
      dockerfile: Dockerfile
      args:
        API_URI: ${WEBAPP_DOMAIN} # e.g. http://localhost
        MAPBOX_TOKEN: ${MAPBOX_TOKEN}
        KEYCLOAK_HOST_URL: ${KEYCLOAK_DOMAIN} # e.g. http://localhost
        COUNT_MESSAGE_TYPES: ${COUNTS_MSG_TYPES}
        DOT_NAME: ${DOT_NAME}
        MAPBOX_INIT_LATITUDE: ${MAPBOX_INIT_LATITUDE}
        MAPBOX_INIT_LONGITUDE: ${MAPBOX_INIT_LONGITUDE}
        MAPBOX_INIT_ZOOM: ${MAPBOX_INIT_ZOOM}
        CVIZ_MAPBOX_TOKEN: ${CVIZ_MAPBOX_TOKEN}
        CVIZ_MAPBOX_STYLE_URL: ${CVIZ_MAPBOX_STYLE_URL}
        CVIZ_API_SERVER_URL: ${CVIZ_API_SERVER_URL}
        CVIZ_API_WS_URL: ${CVIZ_API_WS_URL}
    image: jpo_cvmanager_webapp:latest
    restart: always
    logging:
      options:
        max-size: '10m'
