git mv assessments/ConnectionOfTravelAssessment/* assessments/connection_of_travel_assessment
git mv assessments/LaneDirectionOfTravelAssessment assessments/lane_direction_of_travel_assessment
git mv assessments/SignalStateAssessment assessments/signal_state_assessment
git mv assessments/SignalStateEventAssessment assessments/signal_state_event_assessment

git mv config/DefaultConfig config/default_config
git mv config/IntersectionConfig config/intersection_config

git mv events/BsmEvent events/bsm_event
git mv events/BsmMessageCountProgressionEventRepository events/bsm_message_count_progression_event
git mv events/ConnectionOfTravelEvent events/connection_of_travel_event
git mv events/IntersectionReferenceAlignmentEvent events/intersection_reference_alignment_event
git mv events/LaneDirectionOfTravelEvent events/lane_direction_of_travel_event
git mv events/MapBroadcastRateEvents events/map_broadcast_rate_event
git mv events/MapMessageCountProgressionEventRepository events/map_message_count_progression_event
git mv events/MapMinimumDataEvent events/map_minimum_data_event
git mv events/SignalGroupAlignmentEvent events/signal_group_alignment_event
git mv events/SignalStateConflictEvent events/signal_state_conflict_event
git mv events/SignalStateEvent events/signal_state_event
git mv events/SignalStateStopEvent events/signal_state_stop_event
git mv events/SpatBroadcastRateEvent events/spat_broadcast_rate_event
git mv events/SpatMessageCountProgressionEvent events/spat_message_count_progression_event
git mv events/SpatMinimumDataEvent events/spat_minimum_data_event
git mv events/TimeChangeDetailsEvent events/time_change_details_event

git mv notifications/ActiveNotification notifications/active_notification
git mv notifications/ConnectionOfTravelNotification notifications/connection_of_travel_notification
git mv notifications/IntersectionReferenceAlignmentNotification notifications/intersection_reference_alignment_notification
git mv notifications/LaneDirectionOfTravelNotificationRepo notifications/lane_direction_of_travel_notification
git mv notifications/MapBroadcastRateNotification notifications/map_broadcast_rate_notification
git mv notifications/SignalGroupAlignmentNotificationRepo notifications/signal_group_alignment_notification
git mv notifications/SignalStateConflictNotification notifications/signal_state_conflict_notification
git mv notifications/SpatBroadcastRateNotification notifications/spat_broadcast_rate_notification
git mv notifications/StopLinePassageNotification notifications/stop_line_passage_notification
git mv notifications/StopLineStopNotification notifications/stop_line_stop_notification
git mv notifications/TimeChangeDetailsNotification notifications/time_change_details_notification