version: '3'
services:
  jpo_map_query:
    build: .
    image: map_query:latest
    restart: always
    env_file:
      - .env
    logging:
      options:
        max-size: '10m'
        max-file: '5'
