version: '3'
services:
  jpo_map_query:
    build: .
    image: jpo_map_query:latest
    restart: always
    environment:
      LOGGING_LEVEL: ${LOGGING_LEVEL}
      CONFLUENT: ${CONFLUENT}
      KAFKA_BROKERS: ${KAFKA_BROKERS}
      DEDUP_INPUT_TOPIC: ${DEDUP_INPUT_TOPIC}
      PG_DB_IP: ${PG_DB_IP}
      PG_DB_PORT: ${PG_DB_PORT}
      PG_DB_USER: ${PG_DB_USER}
      PG_DB_PASS: ${PG_DB_PASS}
      PG_DB_NAME: postgres
    logging:
      options:
        max-size: '10m'
        max-file: '5'
