version: '3'
services:
  jpo_geo_msg_query:
    build: .
    image: jpo_geo_msg_query:latest
    restart: always
    environment:
      CONFLUENT: ${CONFLUENT}
      CONFLUENT_KEY: ${CONFLUENT_KEY}
      CONFLUENT_SECRET: ${CONFLUENT_SECRET}
      KAFKA_BROKERS: ${KAFKA_BROKERS}
      GEO_MSG_TYPES: ${GEO_MSG_TYPES}
      MONGO_DB_URI: ${MONGO_DB_URI}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_GEO_COLLECTION: ${MONGO_GEO_COLLECTION}
      MONGO_TTL: ${MONGO_TTL}
      LOGGING_LEVEL: ${LOGGING_LEVEL}
    logging:
      options:
        max-size: '10m'
        max-file: '5'
