apiVersion: v1
kind: Service
metadata:
  name: firmware-manager-svc
  labels:
    app: firmware-manager
spec:
  type: LoadBalancer
  ports:
  - name: firmware-manager-api
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: firmware-manager
---
# Limits the number of pods that are down simultaneously
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: firmware-manager-pdb
spec:
  selector:
    matchLabels:
      app: firmware-manager
  maxUnavailable: 0
---
apiVersion: 'apps/v1'
kind: 'Deployment'
metadata:
  name: firmware-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firmware-manager
  template:
    metadata:
      labels:
        app: firmware-manager
    spec:
      containers:
        - name: firmware-manager
          imagePullPolicy: Always
          image: firmware-manager-image:tag
          resources:
            requests:
              memory: '4Gi'
              cpu: '2'
            limits:
              memory: '4Gi'
              cpu: '2'
          tty: true
          stdin: true
          ports:
            - containerPort: 8080
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/home/secret/cv_credentials.json"
            - name: GCP_PROJECT
              value: ""
            - name: PG_DB_HOST
              value: ""
            - name: PG_DB_NAME
              value: ""
            - name: PG_DB_USER
              valueFrom: 
                secretKeyRef:
                  name: some-postgres-secret-user
                  key: some-postgres-secret-key
            - name: PG_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: some-postgres-secret-password
                  key: some-postgres-secret-key
            - name: BLOB_STORAGE_PROVIDER
              value: ""
            - name: BLOB_STORAGE_BUCKET
              value: ""
            - name: LOGGING_LEVEL
              value: "INFO"
          volumeMounts:
            - name: cv-manager-service-key
              mountPath: /home/secret
          tty: true
          stdin: true
      volumes:
        - name: cv-manager-service-key
          secret:
            secretName: cv-manager-service-key
