apiVersion: v1
kind: Service
metadata:
  name: cv-manager-api-svc
  annotations:
    networking.gke.io/load-balancer-type: 'External'
  labels:
    app: cv-manager-api
spec:
  type: LoadBalancer
  ports:
    - name: api-endpoint
      port: 8080
  selector:
    app: cv-manager-api
---
# limits the number of pods that are down simultaneously
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cv-manager-api-pdb
spec:
  selector:
    matchLabels:
      app: cv-manager-api
  maxUnavailable: 1
---
apiVersion: 'apps/v1'
kind: 'Deployment'
metadata:
  name: cv-manager-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cv-manager-api
  template:
    metadata:
      labels:
        app: cv-manager-api
    spec:
      containers:
        - name: cv-manager-api
          imagePullPolicy: Always
          image: cv-manager-api-image
          resources:
            requests:
              memory: '4Gi'
              cpu: '1'
              ephemeral-storage: '4Gi'
            limits:
              memory: '4Gi'
              cpu: '1'
              ephemeral-storage: '4Gi'
          tty: true
          stdin: true
          ports:
            - containerPort: 8080
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: '/home/secret/cv_credentials.json'
            - name: DB_USER
              value: postgres
            - name: DB_PASS
              value: password
            - name: DB_NAME
              value: postgres
            - name: INSTANCE_CONNECTION_NAME
              value:
            - name: GOOGLE_CLIENT_ID
              value:
            - name: LOGGING_LEVEL
              value: DEBUG
            - name: RSU_REST_ENDPOINT
              value:
            - name: COUNT_DB_NAME
              value:
            - name: TIMEZONE
              value: America/Denver
            - name: WZDX_API_KEY
              value:
            - name: WZDX_ENDPOINT
              value:
            - name: BSM_DB_NAME
              value:
            - name: SSM_DB_NAME
              value:
            - name: SRM_DB_NAME
              value:
          volumeMounts:
            - name: cv-manager-service-key
              mountPath: /home/secret
          tty: true
          stdin: true
      volumes:
        - name: cv-manager-service-key
          secret:
            secretName: cv-manager-service-key
