services:
  rsu-info-bridge:
    image: rsu-info-bridge:0.0.1-SNAPSHOT
    container_name: rsu-info-bridge
    ports:
      - "${RSU_INFO_BRIDGE_PORT:-16543}:${RSU_INFO_BRIDGE_PORT:-16543}"
    environment:
      - RSU_INFO_BRIDGE_PORT=${RSU_INFO_BRIDGE_PORT:-16543}
      - POSTGRES_SERVER_URL=${POSTGRES_SERVER_URL:-jdbc:postgresql://host.docker.internal:5432}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - PG_DB_USER=${PG_DB_USER:-postgres}
      - PG_DB_PASS=${PG_DB_PASS:-postgres}
    env_file:
      - .env
